// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Counter: typeof import('./components/Counter.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/app/Header.vue')['default']
    Hero: typeof import('./components/app/Hero.vue')['default']
    Logo: typeof import('./components/utils/Logo.vue')['default']
    README: typeof import('./components/README.md')['default']
    SwitchTheme: typeof import('./components/utils/SwitchTheme.vue')['default']
  }
}

export { }
